---

version: "2"
services:
  pihole:
    container_name: pihole
    hostname: "{{ pihole_hostname }}"
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "/home/pi/volumes/etc-pihole/:/etc/pihole/"
      - "/home/pi/volumes/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      TZ: "{{ timezone }}"
      WEBPASSWORD: "{{ pihole_webpassword }}"
      VIRTUAL_HOST: "{{ pihole_hostname }}"
