---
- hosts: rpi
  remote_user: pi
  tasks:
  - name: Checkout .dotfiles with git
    git:
      repo: ssh://git@github.com/xnutsive/dotfiles.git
      dest: ~/.dotfiles

  - name: Make sure the .config directory exists
    file:
      path: ~/.config 
      state: directory

  - name: Install dotfiles with dotbot
    shell:
      chdir: ~/.dotfiles
      cmd: ./install
