all:
  children:
    rpi:
      vars:
        ansible_ssh_user: pi
        ansible_python_interpreter: "/usr/bin/python3"
      
      children:

        pizero:
          hosts:
            pizero1.local:
            pizero2.local:

        pi4:
          hosts:
            rpi2.local:
          
          children:
            dockerized:
              hosts:
                rpi1.local:



