---

# Prepare all hosts: install essentials, pass on dotfiles, etc. 
# 
- hosts: all
  roles:
    - ssh-keys
    - prereq

# Make sure dockerized services are up and running
- hosts: docker
  roles:
    - pihole
    - time-machine
