---

# Prepare all hosts: install essentials, pass on dotfiles, etc.
#
- hosts: all
  roles:
    - ssh-keys
    - prereq

- import_playbook: playbooks/pihole.yaml
- import_playbook: playbooks/time-machine.yaml