---

- name: Ensure hfsprogs package is installed
  become: true
  apt:
    name: hfsplus
    state: latest

- name: Stop applications using the partition
  docker_compose:
    state: present
    stopped: true
    project_src: "{{ hfsplus_stop_docker_compose_path }}"
  when: hfsplus_stop_docker_compose_path is defined

- name: Unmount the partition
  become: true
  mount:
    path: "{{ hfsplus_path }}"
    state: unmounted

- name: Ensure the mount point path exists
  become: true
  file:
    path: "{{ hfsplus_path }}"
    state: directory
    owner: root
    group: root
    mode: 0777

- name: Ensure the storage disk is mounted
  become: true
  mount:
    path: "{{ hfsplus_path }}"
    src: "{{ hfsplus_src }}"
    state: mounted
    opts: "force,rw"
    fstype: hfsplus

- name: Copy checkfs script
  become: true
  template:
    src: "checkfs.sh.j2"
    dest: "{{ hfsplus_checkfs_install_dir }}/checkfs.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  when: hfsplus_use_checkfs|bool

- name: Set checkfs to run on @reboot
  cron:
    name: "Check hfsplus FS is writeable"
    job: "{{ hfsplus_checkfs_install_dir }}/checkfs.sh"
    special_time: reboot
    state: present
  when: hfsplus_use_checkfs|bool
