---

- name: Setup SSH keys
  authorized_key:
    user: pi
    state: present
    key: "https://github.com/{{ github_user }}.keys"

- name: Disable password authentication in /etc/ssh/sshd_config
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^(#\s*)?(PasswordAuthentication).*$'
    replace: '\2 no'
  become: true

- name: Disable password authentication in /etc/ssh/sshd_config
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^(#\s*)?(ChallengeResponseAuthentication).*$' 
    replace: '\2 no'
  become: true
