---

- name: Set the timezone.
  become: true
  timezone:
    name: "{{ timezone }}"

- name: Make sure github.com is a known host
  shell: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

- name: Install essential packages
  become: true
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
    update_cache: yes
    state: latest

- name: Upgrade all packages to latest versions
  become: true
  apt:
    name: "*"
    autoclean: yes
    force_apt_get: yes
    update_cache: yes
    state: latest

- name: Checkout .dotfiles with git
  git:
    repo: "ssh://git@github.com/{{ dotfiles_repo }}.git"
    dest: ~/.dotfiles

- name: Make sure the .config directory exists
  file:
    path: ~/.config
    state: directory

# TODO: 
# Check for any files that are in .dotfiles and rm them from ~
# before running this — since dotfiles installer will error
# out if the files already exist. Or, better yet, maybe it has an option
# to force rewrite those?
#
- name: Install dotfiles
  shell:
    chdir: ~/.dotfiles
    cmd: ./install

- name: Set fish as default shell
  shell: chsh -s $(which fish) pi
  become: yes

- name: Install vim plugins
  shell: vim +'PlugInstall --sync' +qa
