---

# TODO:
# For Ubuntu hosts, timezone is set automatically with cloud-init. So this task
# is not relevant.
# Hence this should only run on Raspbian hosts, which can be detected with a
# conditional. Add the conditional execution for this, or maybe even add two
# different roles, prereq-raspbian, and prereq-ubuntu?
#

# - name: Set the timezone.
#   become: true
#   timezone:
#     name: "{{ timezone }}"


- name: Ensure github.com is a known host
  lineinfile:
    dest: "~/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Install essential packages
  become: true
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
    update_cache: yes
    state: latest

# TODO:
# Packages are apdated by defualt with cloud-init in Ubuntu.
#
#   become: true
#   apt:
#     name: "*"
#     autoclean: yes
#     force_apt_get: yes
#     update_cache: yes
#     state: latest

- name: Checkout .dotfiles with git
  git:
    repo: "ssh://git@github.com/{{ dotfiles_repo }}.git"
    dest: ~/.dotfiles

- name: Make sure the .config directory exists
  file:
    path: ~/.config
    state: directory

# TODO:
# Check for any files that are in .dotfiles and rm them from ~
# before running this — since dotfiles installer will error
# out if the files already exist. Or, better yet, maybe it has an option
# to force rewrite those?
#
- name: Install dotfiles
  shell:
    chdir: ~/.dotfiles
    cmd: ./install

# TODO:
# Switch from using shell to using ansible user module.
# That way, it'll signal OK instead of Changed every time
# it runs.
#
- name: Set fish as default shell
  user:
    name: "{{ ansible_user }}"
    shell: "{{ user_shell }}"

- name: Install vim plugins
  shell: vim +'PlugInstall --sync' +qa
