---

- name: Create time machine docker compose path
  file:
    state: directory
    recurse: true
    path: "{{ timemachine_docker_path }}"

- name: Copy docker-compose.yml Pihole spec
  template:
    src: docker-compose.yaml
    dest: "{{ timemachine_docker_path }}docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Run time-machine docker compose service
  docker_compose:
    state: present
    project_src: "{{ timemachine_docker_path }}"
    restarted: true
    pull: true
