---
- hosts: rpi
  remote_user: pi
  vars_files:
    - "../vars/variables.yml"

  tasks:
  - name: Set the timezone.
    become: true
    timezone:
      name: "{{ timezone }}"

  - name: Make sure github.com is a known host
    shell: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

  - name: Checkout .dotfiles with git
    git:
      repo: "ssh://git@github.com/{{ dotfiles_repo }}.git"
      dest: ~/.dotfiles

  - name: Make sure the .config directory exists
    file:
      path: ~/.config
      state: directory

  - name: Install dotfiles
    shell:
      chdir: ~/.dotfiles
      cmd: ./install

  # These two tasks a optional and opinionated:
  # setting my shell to fish and installing vim plugins
  # with a specific plugin manager.
  #
  - name: Set fish as default shell
    shell: chsh -s $(which fish) pi
    become: yes

  - name: Install vim plugins
    shell: vim +'PlugInstall --sync' +qa
