---
- hosts: rpi
  remote_user: pi
  become: yes
  vars_files:
    - "../vars/main.yaml"

  tasks:
  - name: Install essential packages
    apt:
      name: "{{ packages }}"
      force_apt_get: yes
      update_cache: yes
      state: latest

  - name: Upgrade all packages to latest versions
    apt:
      name: "*"
      autoclean: yes
      force_apt_get: yes
      update_cache: yes
      state: latest
