---
- hosts: rpi
  remote_user: pi
  become: yes
  vars_files:
    - "../vars/variables.yml"

  tasks:
  - name: Install essential packages
    apt:
      name: "{{ item }}"
      force_apt_get: yes
      update_cache: yes
      state: latest
    with_items: "{{ packages }}"

  - name: Upgrade all packages to latest versions
    apt:
      name: "*"
      autoclean: yes
      force_apt_get: yes
      update_cache: yes
      state: latest
