---

# TODO Maybe explicitly require geerlingguy.pip role in the 
# playbook instead of having a pip3 playbook?
#

- hosts: dockerized 
  remote_user: pi
  vars_files:
    - "../vars/main.yaml"
    - "../vars/pihole.yaml"

  vars:
    docker_pip_packages:
      - docker
      - docker-compose

  tasks:

    # These three tasks, and the docker-related variables, can be
    # moved into a separate playbook, or better a role. 
    #
  
  - name: Install or update docker
    become: true
    package:
      name: docker
      state: latest

  - name: Install or update required pip3 packages
    pip:
      executable: pip3
      name: "{{ docker_pip_packages }}"
      state: latest

  - name: Ensure docker daemon is running
    service:
      name: docker
      state: started
      enabled: true

  - name: Run pihole/pihole:latest
    docker_compose:
      state: present
      project_name: pihole
      definition:
        version: '2'
        services:
          pihole:
            container_name: compose-pihole
            image: pihole/pihole:latest
            restart: unless-stopped
            ports:
              - "53:53/tcp"
              - "53:53/udp"
              - "67:67/udp"
              - "80:80/tcp"
              - "443:443/tcp"
            volumes:
              - "/home/pi/volumes/etc-pihole/:/etc/pihole/"
              - "/home/pi/volumes/etc-dnsmasq.d/:/etc/dnsmasq.d/"
            dns:
              - 127.0.0.1
              - 1.1.1.1
            environment:
              TZ: "{{ timezone }}"
              WEBPASSWORD: "{{ pihole_webpassword }}"




