---
- hosts: rpi
  remote_user: pi
  vars_files:
    - "../vars/variables.yaml"

  tasks:
  - name: Set SSH keys
    authorized_key:
      user: pi
      state: present
      key: "https://github.com/{{ github_user }}.keys"

  - name: Disable password authentication
    copy:
      src: "../files/sshd_config"
      dest: "/etc/ssh/"
      force: yes
      backup: yes
    become: true
