name: Linters
on: [push, pull_request]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
        python-version: "3.7"
        architecture: 'x64'

    - name: Install dev dependencies
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Lint the playbooks and roles
      run: pipenv run ansible-lint

