name: Linters
on: [push, pull_request]
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Install dev dependencies
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Lint the playbooks and roles
      run: pipenv run ansible-lint

