---

- name: Make sure dnsmasq.d volume directory exists
  file:
    path: "/home/pi/volumes/etc-dnsmasq.d"
    state: directory
    recurse: yes

- name: Upload dnsmasq config
  copy:
    src: "02-hosts.conf"
    dest: "/home/{{ ansible_user }}/volumes/etc-dnsmasq.d/02-hosts.conf"

- name: Ensure Pihole spec directory exists
  file:
    state: directory
    recurse: true
    path: "{{ pihole_docker_path }}"

- name: Copy docker-compose.yml Pihole spec
  template:
    src: docker-compose.yaml
    dest: "{{ pihole_docker_path }}docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Run pihole/pihole:latest
  docker_compose:
    state: present
    project_src: "{{ pihole_docker_path }}" 
    pull: true
    restarted: true
