---

- name: Make sure dnsmasq.d volume directory exists
  file:
    path: "{{ pihole_volume_etc_dnsmasqd }}"
    state: directory
    recurse: yes

- name: Upload dnsmasq config
  template:
    src: "02-hosts.conf.j2"
    dest: "{{ pihole_volume_etc_dnsmasqd }}/02-hosts.conf"

- name: Ensure Pihole spec directory exists
  file:
    state: directory
    recurse: true
    path: "{{ pihole_docker_path }}"

- name: Copy docker-compose.yml Pihole spec
  template:
    src: docker-compose.yaml.j2
    dest: "{{ pihole_docker_path }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Run pihole/pihole:latest
  docker_compose:
    state: present
    project_src: "{{ pihole_docker_path }}"
    pull: true
    restarted: true
